service: eventbridge-demo
 
provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - events:PutEvents
          Resource: arn:aws:events:ap-south-1:203918851056:event-bus/dev-test
 
functions:
  eventDispatcher:
    handler: handler.dispatchEvent
    events:
      - http:
          path: dispatch
          method: post
 
  eventConsumer:
    handler: handler.consumeEvent
    events:
      - eventBridge:
          eventBus: arn:aws:events:ap-south-1:203918851056:event-bus/dev-test
          pattern:
            source:
              - testingSource
            detail-type:
              - myEvent
      - http:
          path: consume
          method: post

resources:
  Resources:
    MyEventRule:
      Type: AWS::Events::Rule
      Properties:
        Name: MyEventRule
        EventBusName:  arn:aws:events:ap-south-1:203918851056:event-bus/dev-test
        EventPattern:
          source:
            - testingSource
          detail-type:
            - myEvent
        State: ENABLED
        Targets:
          - Id: TargetFunctionV1
            Arn: 
              Fn::GetAtt:
                - EventConsumerLambdaFunction
                - Arn
 
 
plugins:
  - serverless-offline